<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'CreateTaggedTable' => $baseDir . '/database/migrations/2014_01_07_073615_create_tagged_table.php',
    'CreateTagsTable' => $baseDir . '/database/migrations/2014_01_07_073615_create_tags_table.php',
    'DatabaseSeeder' => $baseDir . '/database/seeds/DatabaseSeeder.php',
    'IlluminateQueueClosure' => $vendorDir . '/illuminate/queue/IlluminateQueueClosure.php',
);
